In [4]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [12]:
def extraer_datos(tipo, num):
    if(tipo == "electrico"):
        datos = os.path.join( '.',os.path.join('data_'+ tipo,'VBS__'+str(num)+ '.VBO'))
        data_pd = pd.read_csv(datos, sep=' ',header=None , skiprows=69)

    if(tipo == "combustion"):
        datos = os.path.join( '.',os.path.join('data_'+ tipo,'VBOX'+str(num)+ '.VBO'))
        data_pd = pd.read_csv(datos, sep=' ',header=None , skiprows=35)        
    
    return data_pd

In [13]:
a=extraer_datos("combustion","0018")
a

     0          1    2    3    4    5    6    7         8    9   10
0     0  142505.09  0.0 -0.0  0.0  0.0  0.0  0.0  0.002202  0.0 NaN
1     0  142505.10  0.0 -0.0  0.0  0.0  0.0  0.0  0.002315  0.0 NaN
2     0  142505.11  0.0 -0.0  0.0  0.0  0.0  0.0  0.002155  0.0 NaN
3     0  142505.12  0.0 -0.0  0.0  0.0  0.0  0.0  0.002262  0.0 NaN
4     0  142505.13  0.0 -0.0  0.0  0.0  0.0  0.0  0.002282  0.0 NaN
5     0  142505.14  0.0 -0.0  0.0  0.0  0.0  0.0  0.002375  0.0 NaN
6     0  142505.15  0.0 -0.0  0.0  0.0  0.0  0.0  0.002315  0.0 NaN
7     0  142505.16  0.0 -0.0  0.0  0.0  0.0  0.0  0.002155  0.0 NaN
8     0  142505.17  0.0 -0.0  0.0  0.0  0.0  0.0  0.002162  0.0 NaN
9     0  142505.18  0.0 -0.0  0.0  0.0  0.0  0.0  0.002149  0.0 NaN
10    0  142505.19  0.0 -0.0  0.0  0.0  0.0  0.0  0.002315  0.0 NaN
11    0  142505.20  0.0 -0.0  0.0  0.0  0.0  0.0  0.002315  0.0 NaN
12    0  142505.21  0.0 -0.0  0.0  0.0  0.0  0.0  0.002289  0.0 NaN
13    0  142505.22  0.0 -0.0  0.0  0.0  0.0  0.0  0.002162  0.0 NaN
14    0  142505.23  0.0 -0.0  0.0  0.0  0.0  0.0  0.002249  0.0 NaN
15    0  142505.24  0.0 -0.0  0.0  0.0  0.0  0.0  0.002282  0.0 NaN
16    0  142505.25  0.0 -0.0  0.0  0.0  0.0  0.0  0.002169  0.0 NaN
17    0  142505.26  0.0 -0.0  0.0  0.0  0.0  0.0  0.002209  0.0 NaN
18    0  142505.27  0.0 -0.0  0.0  0.0  0.0  0.0  0.002275  0.0 NaN
19    0  142505.28  0.0 -0.0  0.0  0.0  0.0  0.0  0.002309  0.0 NaN
20    0  142505.29  0.0 -0.0  0.0  0.0  0.0  0.0  0.002322  0.0 NaN
21    0  142505.30  0.0 -0.0  0.0  0.0  0.0  0.0  0.002189  0.0 NaN
22    0  142505.31  0.0 -0.0  0.0  0.0  0.0  0.0  0.002349  0.0 NaN
23    0  142505.32  0.0 -0.0  0.0  0.0  0.0  0.0  0.002155  0.0 NaN
24    0  142505.33  0.0 -0.0  0.0  0.0  0.0  0.0  0.002182  0.0 NaN
25    0  142505.34  0.0 -0.0  0.0  0.0  0.0  0.0  0.002235  0.0 NaN
26    0  142505.35  0.0 -0.0  0.0  0.0  0.0  0.0  0.002175  0.0 NaN
27    0  142505.36  0.0 -0.0  0.0  0.0  0.0  0.0  0.002322  0.0 NaN
28    0  142505.37  0.0 -0.0  0.0  0.0  0.0  0.0  0.002309  0.0 NaN
29    0  142505.38  0.0 -0.0  0.0  0.0  0.0  0.0  0.002289  0.0 NaN
..   ..        ...  ...  ...  ...  ...  ...  ...       ...  ...  ..
795   0  142513.04  0.0 -0.0  0.0  0.0  0.0  0.0  0.002195  0.0 NaN
796   0  142513.05  0.0 -0.0  0.0  0.0  0.0  0.0  0.002269  0.0 NaN
797   0  142513.06  0.0 -0.0  0.0  0.0  0.0  0.0  0.002282  0.0 NaN
798   0  142513.07  0.0 -0.0  0.0  0.0  0.0  0.0  0.002202  0.0 NaN
799   0  142513.08  0.0 -0.0  0.0  0.0  0.0  0.0  0.002315  0.0 NaN
800   0  142513.09  0.0 -0.0  0.0  0.0  0.0  0.0  0.002322  0.0 NaN
801   0  142513.10  0.0 -0.0  0.0  0.0  0.0  0.0  0.002215  0.0 NaN
802   0  142513.11  0.0 -0.0  0.0  0.0  0.0  0.0  0.002255  0.0 NaN
803   0  142513.12  0.0 -0.0  0.0  0.0  0.0  0.0  0.002175  0.0 NaN
804   0  142513.13  0.0 -0.0  0.0  0.0  0.0  0.0  0.002182  0.0 NaN
805   0  142513.14  0.0 -0.0  0.0  0.0  0.0  0.0  0.002302  0.0 NaN
806   0  142513.15  0.0 -0.0  0.0  0.0  0.0  0.0  0.002269  0.0 NaN
807   0  142513.16  0.0 -0.0  0.0  0.0  0.0  0.0  0.002195  0.0 NaN
808   0  142513.17  0.0 -0.0  0.0  0.0  0.0  0.0  0.002302  0.0 NaN
809   0  142513.18  0.0 -0.0  0.0  0.0  0.0  0.0  0.002182  0.0 NaN
810   0  142513.19  0.0 -0.0  0.0  0.0  0.0  0.0  0.002415  0.0 NaN
811   0  142513.20  0.0 -0.0  0.0  0.0  0.0  0.0  0.002175  0.0 NaN
812   0  142513.21  0.0 -0.0  0.0  0.0  0.0  0.0  0.002262  0.0 NaN
813   0  142513.22  0.0 -0.0  0.0  0.0  0.0  0.0  0.002302  0.0 NaN
814   0  142513.23  0.0 -0.0  0.0  0.0  0.0  0.0  0.002302  0.0 NaN
815   0  142513.24  0.0 -0.0  0.0  0.0  0.0  0.0  0.002289  0.0 NaN
816   0  142513.25  0.0 -0.0  0.0  0.0  0.0  0.0  0.002175  0.0 NaN
817   0  142513.26  0.0 -0.0  0.0  0.0  0.0  0.0  0.002282  0.0 NaN
818   0  142513.27  0.0 -0.0  0.0  0.0  0.0  0.0  0.002169  0.0 NaN
819   0  142513.28  0.0 -0.0  0.0  0.0  0.0  0.0  0.002255  0.0 NaN
820   0  142513.29  0.0 -0.0  0.0  0.0  0.0  0.0  0.002295  0.0 NaN
821   0  142513.30  0.0 -0.0  0.0  0.0  0.0  0.0  0.002162  0.0 NaN
822   0  142513.31  0.0 -0.0  0.0  0.0  0.0  0.0  0.002289  0.0 NaN
823   0  142513.32  0.0 -0.0  0.0  0.0  0.0  0.0  0.002182  0.0 NaN
824   0  142513.33  0.0 -0.0  0.0  0.0  0.0  0.0  0.002295  0.0 NaN

[825 rows x 11 columns]